### ISSUE TITLE
Operation log storage exception

### ISSUE THREAD

**Issue by downdawn** [fastapi-practices/fastapi_best_architecture#128]
![1686712535439](https://github.com/fastapi-practices/fastapi_best_architecture/assets/41266749/4f3f8252-9b1b-4b34-b43e-230b15493cd4)

[https://github.com/zzzeek/sqlalchemy/blob/main/lib/sqlalchemy/exc.py](https://github.com/zzzeek/sqlalchemy/blob/main/lib/sqlalchemy/exc.py)

code type may be a string

Msg may not need to report error stack information?

**Comment by wu-clan** [comment]
I think yes

the code is allowed to use the string type

msg errors are written directly to the log file and not stored in the database
