### ISSUE TITLE
get_request_args Exception

### ISSUE THREAD

**Issue by downdawn** [fastapi-practices/fastapi_best_architecture#138]
When the API request parameters are missing and request.json() fails to parse, proper error handling should be implemented.
```

            body_data = await request.body()
            if body_data:
                try:
                    json_data = await request.json()
                    args.update(json_data)
                except Exception as e:
                    log.exception(e)
                    args.update({'body': body_data.decode('utf-8')})
```

**Comment by wu-clan** [comment]
This processing will cause the data encryption to fail. What is the specific case where the json() parsing fails?

**Comment by downdawn** [comment]
Missing required parameters result in an error. For example, when making a request to the login API, if only the username and password are provided without the captcha, an error will be thrown.
```
{
  "code": 422,
  "msg": "请求参数非法: captcha field required.",
  "data": null
}
```

The password will be encrypted, but the code will not match.
In the operation log, the code is shown as 200, but it should actually be 422.

![image](https://github.com/fastapi-practices/fastapi_best_architecture/assets/41266749/2d2e0d5f-33f6-4749-87ef-f7a2436ab06d)

**Comment by wu-clan** [comment]
But this doesn't seem to be an error in request.json(), I don't think request.json() seems to throw an exception here because the data validation is triggered earlier

**Comment by wu-clan** [comment]
execute_request() seems to catch only explicit exceptions, i.e. internal errors that are printed on the console, and fastapi handles data validation as 422 request success instead of triggering an exception

**Comment by wu-clan** [comment]
fastapi internally calls an exception handler before the request is sent

https://github.com/tiangolo/fastapi/blob/49bc3e0873c8e89edbffdd3a41b1c2c56f15c823/fastapi/applications.py#L142C12-L148

After the exception handling is triggered, `return JSONResponse()` is called directly, so execute_request() does not catch the exception

**Comment by wu-clan** [comment]
Test Pass.

![image](https://github.com/fastapi-practices/fastapi_best_architecture/assets/52145145/a056f92c-0e8a-4200-95c7-a3d03f8bd473)
