### ISSUE TITLE
get_cpu_info exception

### ISSUE THREAD

**Issue by downdawn** [fastapi-practices/fastapi_best_architecture#139]
windows10
```
    total = cpu_times.user + cpu_times.nice + cpu_times.system + cpu_times.idle \
AttributeError: 'scputimes' object has no attribute 'nice'
```

**Comment by wu-clan** [comment]
This seems to be directly related to the CPU model

My local environment:

- Windows11
- CPU: AMD Ryzen 5 5600X 6-Core Processor 4.20 GHz

**Comment by downdawn** [comment]
Platform-specific fields

[https://psutil.readthedocs.io/en/latest/#cpu](https://psutil.readthedocs.io/en/latest/#cpu)

public fields: user、system、idle

**Comment by wu-clan** [comment]
I think I understand why I ran it successfully, because I started the project with WSL and it was actually running on Ubuntu (Linux)
