### ISSUE TITLE
Tree data algorithms exception

### ISSUE THREAD

**Issue by downdawn** [fastapi-practices/fastapi_best_architecture#168]
![image](https://github.com/fastapi-practices/fastapi_best_architecture/assets/41266749/a78fbe6a-cb3a-4799-aa95-d47c363c37ab)
![image](https://github.com/fastapi-practices/fastapi_best_architecture/assets/41266749/0152dfca-66f8-4352-9cab-0e56c8cf467d)

**Comment by downdawn** [comment]
Algorithm problem caused id5 to not query the sub-level id6, so the login log page cannot be displayed.
![image](https://github.com/fastapi-practices/fastapi_best_architecture/assets/41266749/c48994c6-a506-42a5-b511-7bddd1d0a255)

**Comment by wu-clan** [comment]
But I do not encounter this exception locally, all subsets are displayed normally

**Comment by wu-clan** [comment]
Yes, I checked the algorithm again and it is now affected by the order of the data and if the subset is before the parent, it will not be displayed
