### ISSUE TITLE
Migrating to Pydantic V2

### ISSUE THREAD

**Issue by downdawn** [fastapi-practices/fastapi_best_architecture#180]
[https://docs.pydantic.dev/dev-v2/migration/](https://docs.pydantic.dev/dev-v2/migration/)

**Comment by downdawn** [comment]
known open issues：

[https://github.com/pydantic/pydantic/issues/5651](https://github.com/pydantic/pydantic/issues/5651)

[https://github.com/pydantic/pydantic/issues/6375](https://github.com/pydantic/pydantic/issues/6375)

**Comment by wu-clan** [comment]
My thoughts:

1. I wanted to wait for fastapi to be released after two more releases, because you have to upgrade it to use PV2
2. PV2 may be a new branch, but will act as the master branch
3. Make PV1 the old branch and lock it

The reason for the branch is: we may have to change a lot in the error messages and exception blockers for PV2, I'm not sure

**Comment by wu-clan** [comment]
Yes, those things were written according to their internal logic, which changed in the new version, so they had to be rewritten

**Comment by wu-clan** [comment]
V2 custom content can be referenced:

https://github.com/fastapi-practices/fastapi_tortoise_mysql/blob/f014b74552de20a56b9851782050acd874fbbdc7/backend/app/common/exception/exception_handler.py#L48

https://github.com/fastapi-practices/fastapi_tortoise_mysql/blob/f014b74552de20a56b9851782050acd874fbbdc7/backend/app/schemas/base.py

https://github.com/fastapi-practices/fastapi_tortoise_mysql/blob/f014b74552de20a56b9851782050acd874fbbdc7/backend/app/common/pagination.py#L66

Please note that this reference is an experimental upgrade and has not been extensively tested

**Comment by wu-clan** [comment]
Auxiliary: https://github.com/pydantic/pydantic/issues/7224

**Comment by wu-clan** [comment]
Have you gone through extensive validation of pydantic-v2? Perhaps we need to finish this PR first, I'm basically using V2 in other repositories, but I haven't tested it extensively.

And known issues:
- json_encoder incompatibility
- enum type error not accurately caught

**Comment by isooops** [comment]
大佬，加油更pydantic v2啊， 等着瞻仰学习呢

**Comment by wu-clan** [comment]
The work is in progress, but it may not be as fast as expected. We need testers.

**Comment by wu-clan** [comment]
The work is going well. I think all the work has been basically completed. I have conducted a simple test locally, and they look good.

The only problem now is that no equivalent substitute for json_encoder can be found.

View https://github.com/tiangolo/fastapi/discussions/10252#discussioncomment-7880419

**Comment by wu-clan** [comment]
We mainly use the json_encoder serialization time format internally, and if it is not available, it means that we may return an inconsistent time field format.

**Comment by downdawn** [comment]
[https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.json_encoders](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.json_encoders)

In v2 version, it has been deprecated. We can only wait for a solution.

**Comment by wu-clan** [comment]
Therefore, my plan is to first merge the branches and accomplish the following:

- [ ] Set v2 as the main branch (master), and rename the v1 branch to pydantic-v1.
- [ ] Clean up the code used for testing in the v1 branch.
- [ ] Lock the v1 branch, no longer updating or fixing it.
- [ ] Add documentation for this update in different branches.
