### ISSUE TITLE
Enum exception

### ISSUE THREAD

**Issue by downdawn** [fastapi-practices/fastapi_best_architecture#184]
The get request sets the enumeration value and throws an exception
```
async def get_all_menus(
    title: Annotated[str | None, Query()] = None,
    status: Annotated[StatusType | None, Query()] = None,
):
```
```
{
  "code": 422,
  "msg": "请求参数非法",
  "data": {
    "errors": [
      {
        "loc": [
          "query",
          "status"
        ],
        "msg": "value is not a valid enumeration member; permitted: 0, 1",
        "type": "type_error.enum",
        "ctx": {
          "enum_values": [
            0,
            1
          ]
        }
      }
    ]
  }
}
```

The post request set enumeration value is invalid

For example, when creating a menu, although the MenuType is set, it is still possible to set data exceeding the limit

**Comment by wu-clan** [comment]
Field conditions cause this problem, deleting the ge will fix it.

**Comment by downdawn** [comment]
> Field conditions cause this problem, deleting the ge will fix it.

This will fix the post

**Comment by downdawn** [comment]
It is recommended to add a unified suffix to all enumeration types, just like StatusEnum

**Comment by wu-clan** [comment]
I'm better at using Type as a suffix.
