### ISSUE TITLE
console log output missing time

### ISSUE THREAD

**Issue by downdawn** [fastapi-practices/fastapi_best_architecture#209]
Hi, @wu-clan 

Missing crucial time data, is there a way to customize the output?

```
INFO:     127.0.0.1:0 - "GET /api/v1/menus/sidebar HTTP/1.0" 200 OK
```

**Comment by wu-clan** [comment]
We've added database request logging

Adding log file records is easy

This printout is from uvicorn, I'm not sure if it's possible to add the time information

**Comment by downdawn** [comment]
```
        log_config = uvicorn.config.LOGGING_CONFIG
        fmt = "%(levelprefix)s %(client_addr)s - %(asctime)s - \"%(request_line)s\" %(status_code)s"
        log_config["formatters"]["access"]["fmt"] = fmt
        uvicorn.run(
            app=f'{Path(__file__).stem}:app',
            host=settings.UVICORN_HOST,
            port=settings.UVICORN_PORT,
            reload=settings.UVICORN_RELOAD,
        )
```
This configuration can output time information normally locally, but deployment with gunicorn+supervisor still does not take effect.

**Comment by downdawn** [comment]
[https://github.com/benoitc/gunicorn/issues/2404](https://github.com/benoitc/gunicorn/issues/2404)
[https://github.com/encode/uvicorn/issues/527](https://github.com/encode/uvicorn/issues/527)

**Comment by wu-clan** [comment]
It seems to me that the officials don't care about prioritizing this and there's nothing we can do about it

**Comment by wu-clan** [comment]
uvicorn 0.30.0 released. 

Not sure if this problem has been solved, if you are interested, please try.

**Comment by wu-clan** [comment]
If you want to set up gunicorn logs, refer to: https://gist.github.com/dishwad/c9b24ee7f9c5c710bae4c2f31d8667a7
