### ISSUE TITLE
Upgrade python base version to python 3.10

### ISSUE THREAD

**Issue by wu-clan** [fastapi-practices/fastapi_best_architecture#23]
### Discussed in #22

<div type='discussions-op-text'>

<sup>Originally posted by **downdawn** April 25, 2023</sup>
## 5. Use python3.10 version

The pre-commit configuration specifies version 3.10 by default, and some new features can be used later, of course, compatibility should also be considered

[https://fastapi.tiangolo.com/python-types/#newer-versions-of-python](https://fastapi.tiangolo.com/python-types/#newer-versions-of-python)
</div>

**Comment by wu-clan** [comment]
I am doing this work based on Python 3.8, but even if I add `from __future__ Import annotations`, I cannot use the `|` flag either

**Comment by wu-clan** [comment]
Hi, @downdawn 

Is it convenient for you to perform the test?

I may lose my coding on May 1st because I don't have a laptop and I can only reply to messages via my phone

**Comment by downdawn** [comment]
Using the | symbol to separate is a feature of python3.10+

[https://fastapi.tiangolo.com/python-types/#union](https://fastapi.tiangolo.com/python-types/#union)

![image](https://user-images.githubusercontent.com/41266749/235115605-9d66ede3-bb85-4c44-97d3-337b7f81a060.png)

In the local win environment, I use conda to manage the switching environment, and in the Linux environment, I use pyenv. I can test different python versions.

**Comment by wu-clan** [comment]
Yes, but the library based on 3.10 encoding can run in the lower version. I didn’t find the relevant PEP, so I‘m a little confused.

If you just replace it with Union, it is very convenient, [no-optional](https://github.com/Kludex/no-optional)

**Comment by downdawn** [comment]
python3.10+ can run directly

```
def process_item(item: int | str):
    print(item, type(item))


if __name__ == '__main__':
    process_item(1)  # 1 <class 'int'>
    process_item("1")  # 1 <class 'str'>
```

python3.7-3.9 can import `from __future__ import annotations` run

**Comment by downdawn** [comment]
After testing, no_optiona can replace `Optional[str] = None` with `Union[str, None] = None`

Can be used in pre-commit.

**Comment by wu-clan** [comment]
> python3.10+ can run directly
> 
> 
> 
> ```
> 
> def process_item(item: int | str):
> 
>     print(item, type(item))
> 
> 
> 
> 
> 
> if __name__ == '__main__':
> 
>     process_item(1)  # 1 <class 'int'>
> 
>     process_item("1")  # 1 <class 'str'>
> 
> ```
> 
> 
> 
> python3.7-3.9 can import `from __future__ import annotations` run
> 
Yes, This is expected.

There should be some problems in my submission that caused the error.

**Comment by wu-clan** [comment]
> After testing, no_optiona can replace `Optional[str] = None` with `Union[str, None] = None`
> 
> 
> 
> Can be used in pre-commit.

If we use PEP563, this scheme will not be needed. I have updated it to `|` through ruff.

**Comment by wu-clan** [comment]
We will use PEP586 and PEP589 to a large extent.

So it should start directly from py3.8.

**Comment by downdawn** [comment]
OK
