### ISSUE TITLE
celery task exception

### ISSUE THREAD

**Issue by downdawn** [fastapi-practices/fastapi_best_architecture#238]
When I was testing the task of sending an email, an exception occurred:
```
@celery_app.task
def send_active_email(email: str, active_url: str) -> str:
    send_verification_code_email(to=email, active_url=active_url)
    print(f'发送激活邮件到 {email} 成功')
    return 'Success'
```
KeyError: 'backend.app.tasks.send_active_email'

Request interface: `/api/v1/mixes/tests/send`

KeyError: 'backend.app.tasks.task_demo_async'

```
Received unregistered task of type 'backend.app.tasks.task_demo_async'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

```

**Comment by wu-clan** [comment]
Hi, @downdawn 

Can you provide startup logs for celery? I think you use this command to start celery: `celery -A tasks worker --loglevel=INFO`

**Comment by wu-clan** [comment]
Please note the list of tasks：

![image](https://github.com/fastapi-practices/fastapi_best_architecture/assets/52145145/3d4514cf-b489-4875-94d8-dcac53ad7c7a)

**Comment by downdawn** [comment]
![image](https://github.com/fastapi-practices/fastapi_best_architecture/assets/41266749/add969df-9972-4ec4-be74-df73bbeee252)
![image](https://github.com/fastapi-practices/fastapi_best_architecture/assets/41266749/4caa90f6-27d2-4935-90c0-0e7b0f2bbeae)

**Comment by downdawn** [comment]
I think I understand a bit now. The task registered is tasks.task_demo_async, but the task executed by the /api/v1/mixes/tests/send endpoint is backend.app.tasks.task_demo_async.

**Comment by wu-clan** [comment]
Yes, the `app.autodiscover_tasks(packages=['backend.app'])` in PR doesn't work for you?

**Comment by wu-clan** [comment]
Or, as a last resort, try `celery_app.send_task('task_demo_async')`

**Comment by downdawn** [comment]
> Yes, the `app.autodiscover_tasks(packages=['backend.app'])` in PR doesn't work for you?

Already working,
Sorry, I didn't see `packages=['backend.app']`...
