### ISSUE TITLE
Argument 'value' has incorrect type (expected str, got UUID)

### ISSUE THREAD

**Issue by Yuwenqing** [fastapi-practices/fastapi_best_architecture#240]
当新建用户时，遇到如下报错
  File "asyncmy\converters.pyx", line 26, in asyncmy.converters.escape_item
    val = encoder(val, mapping)
TypeError: Argument 'value' has incorrect type (expected str, got UUID)

asyncmy   0.2.8
Mysql       8.1.0

**Comment by wu-clan** [comment]
This issue is being fixed as much as possible.
