### ISSUE TITLE
curd/base.py 有个问题

### ISSUE THREAD

**Issue by jundaychan** [fastapi-practices/fastapi_best_architecture#268]
get_方法，当主键 pk 为 1 的时候会卡死，可能识别错误，所以*解包应该是不太能用，

**Comment by wu-clan** [comment]
我在本地测试中没有遇到此错误:
```bash
curl -X 'GET' \
  'http://127.0.0.1:8000/api/v1/depts/1' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDQ5NzkwMjUsInN1YiI6IjIifQ.0ciKz_asssLjZw7B-F7q-ZCT_OPtlW2JuLy1XvoKRwg'
```
```python
{
  "code": 200,
  "msg": "请求成功",
  "data": {
    "name": "test",
    "parent_id": null,
    "sort": 0,
    "leader": null,
    "phone": null,
    "email": null,
    "status": 1,
    "id": 1,
    "del_flag": false,
    "created_time": "2023-06-26T17:13:45",
    "updated_time": "2023-08-11T15:18:33"
  }
}
```

**Comment by wu-clan** [comment]
我们有一个关于 CRUDBase 的讨论：https://github.com/fastapi-practices/fastapi_best_architecture/discussions/267，如果你有兴趣，欢迎提供建议

**Comment by wu-clan** [comment]
我们有一个关于 CRUDBase 的讨论：https://github.com/fastapi-practices/fastapi_best_architecture/discussions/267 

如果你有兴趣，欢迎提供建议

**Comment by jundaychan** [comment]
这是我的 model，

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from datetime import datetime

from sqlalchemy import String
from sqlalchemy.orm import Mapped, mapped_column

from backend.app.models.base import DataClassBase, id_key

from backend.app.utils.timezone import timezone


class Knowledge(DataClassBase):
    """
    知识库表
    """

    __tablename__ = 'knowledge'

    dept_id: Mapped[int | None] = mapped_column(comment='部门ID')
    id: Mapped[id_key] = mapped_column(init=False)
    name: Mapped[str] =  mapped_column(String(52),default=None,comment='知识库名称')
    description: Mapped[str | None] = mapped_column(String(255),default=None,comment='描述')
    model: Mapped[str | None] = mapped_column(String(32),default=None,comment='模型')
    index_name: Mapped[str | None] = mapped_column(String(32),default=None,comment='索引名称')
    collection_name: Mapped[str | None] = mapped_column(String(32),default=None,comment='集合名称')
    is_partition: bool = True
    created_time: Mapped[datetime] = mapped_column(init=False, default_factory=timezone.now, comment='创建时间')
    updated_time: Mapped[datetime] = mapped_column(init=False, default_factory=timezone.now, comment='更新时间')


目前卡在了result = await db.execute(select(self.model).where(and_(*where_list)))

**Comment by wu-clan** [comment]
`is_partition: bool = True`?

Why not `is_partition: Mapped[bool] = mapped_column(default=True)`?

你尝试过使用`await db.execute(select(self.model).where(self.model.id == pk))`是否能正确返回码？

另外，你完全可以继承 Base，从而省略手动编写的 created_time 和 updated_time

**Comment by wu-clan** [comment]
If there is no feedback, I will close this problem.
