### ISSUE TITLE
建议新增代码生成功能

### ISSUE THREAD

**Issue by jundaychan** [fastapi-practices/fastapi_best_architecture#279]
目前看到三层结构比较完善，使用也很容易，建议作者考虑用 tpl 模版来做代码生成，这样会大幅度提高写接口速度；

可以参考 gin-vue-admin

**Comment by wu-clan** [comment]
这个在 TODO 中已经包含并存在已久，已经在进行，当我在本地编码和调试通过后，会提交 PR，虽然...，但是...，我的业余时间目前非常少，复杂功能更新会很慢
