### ISSUE TITLE
some things

### ISSUE THREAD

**Issue by MatsiukMykola** [fastapi-practices/fastapi_best_architecture#280]
think you have a good point, but some things:
1. translate everything to English language, this help extend interesting to you project
2. try to use fastapi-amis-admin
3. use modern poetry and ruff

**Comment by wu-clan** [comment]
Hi, @MatsiukMykola 

Thank you for your valuable suggestions, here are some of my ideas

1. we will try to provide English as much as possible, update later
2. amis is not our route, vue / react is better for us
3. we'll add pdm if needed, it's higher priority than poetry
4. ruff is in use, I'll try to restore ci
