### ISSUE TITLE
use pydantic EmailStr for email validation

### ISSUE THREAD

**Issue by Festus-Kwafo** [fastapi-practices/fastapi_best_architecture#289]

**Comment by wu-clan** [comment]
Hi， @Festus-Kwafo 

Can you describe your problem in detail?

**Comment by Festus-Kwafo** [comment]
So with the upgrade of pydantic to v2. I think it is redundant to write a function to check email if that will be done with EmailStr that has embedded in the new updates.

**Comment by wu-clan** [comment]
I didn't find such a function in the current branch, so I can't understand the problem because we're already using EmailStr.

**Comment by Festus-Kwafo** [comment]
yeah sure. it has been updated. Thank you
