### ISSUE TITLE
demo 网站出问题了： 内部服务器错误。

### ISSUE THREAD

**Issue by EsqerYasen** [fastapi-practices/fastapi_best_architecture#297]

**Comment by wu-clan** [comment]
线上数据库不小心被我删了...

今天我会再试图恢复一下，不行就重新部署了

**Comment by wu-clan** [comment]
不小心编辑了你的评论😅

线上数据库不小心被我删了...

今天我会再试图恢复一下，不行就重新部署了

**Comment by EsqerYasen** [comment]
> 不小心编辑了你的评论😅
> 
> 线上数据库不小心被我删了...
> 
> 今天我会再试图恢复一下，不行就重新部署了

谢谢回复，在本地的话，怎么样才能禁用验证码登录呢？

**Comment by EsqerYasen** [comment]
我已经启动，但是还是停留在验证码部分😅

**Comment by wu-clan** [comment]
禁用验证码改前端源码就行了

**Comment by wu-clan** [comment]
线上环境已恢复
