### ISSUE TITLE
❔ questions database

### ISSUE THREAD

**Issue by Yurgers** [fastapi-practices/fastapi_best_architecture#320]
I'm trying to figure out this project.
the project is very cool.
I have some questions that could help me.

What the tables are used for: sys_dict_data and sys_dict_type,
their presence is completely unclear to me.

And I got confused about the rights...
- there is a column `perms` in the table `sys_menu`
- there are `Depends(requestPermission('xxx'))`
- and also, there is also a table `sys_casbin_rule`

which of these should be used?

**Comment by wu-clan** [comment]
1. `sys_dict_ data`and `sys_dict_ type` is used for front-end, but it has not been implemented in the front-end yet. 
2. `perms` and `perms` (requestPermission ('xxx')) `are used for menu routing permissions. (Simple)
3. `sys_casbin_rule` is used for casbin rbac. (Complex)

**Comment by wu-clan** [comment]
The official documentation hasn't started yet for a number of reasons, but I'm still working on it.

**Comment by Yurgers** [comment]
maybe there is no official documentation. Some kind of draft?

it would be great if there was at least a brief reference on the rights.
what is their logic, the principle of operation.

**Comment by Yurgers** [comment]
is there an opportunity to show an example of filling in the sys_casbin_rule table?

**Comment by wu-clan** [comment]
Unfortunately, there is no document description at present. Casbin is a complex permission system. I think you need to study the official documents in depth.
