### ISSUE TITLE
Celery with asyncio?

### ISSUE THREAD

**Issue by downdawn** [fastapi-practices/fastapi_best_architecture#321]
Hi, @wu-clan 

Celery scheduled tasks cannot be executed

![bdb52e620133cb39d87751f53ed28ea](https://github.com/fastapi-practices/fastapi_best_architecture/assets/41266749/2ffb9a9d-73be-4d17-861b-9db24849fd3e)

Solutions related to asyncio
[https://stackoverflow.com/questions/39815771/how-to-combine-celery-with-asyncio](https://stackoverflow.com/questions/39815771/how-to-combine-celery-with-asyncio)

![5b0e766934b4c6826ddfc9611064a87](https://github.com/fastapi-practices/fastapi_best_architecture/assets/41266749/802885df-6b62-4357-85eb-9637718ac3d2)

The method above uses async_to_sync to forcibly convert to a synchronous method, which runs normally on the Windows 10 system, but requires additional configuration.

```
# windows 下需要设置环境变量,不推荐使用 windows 下开发 celery
# https://github.com/celery/celery/pull/4078
#
import os

os.environ.setdefault('FORKED_BY_MULTIPROCESSING', '1')
```

In the CentOS 7 system environment, after deployment using Supervisor and Gunicorn, observe it several times and an exception may occur.
![image](https://github.com/fastapi-practices/fastapi_best_architecture/assets/41266749/675f2c92-5b8a-4578-bda6-6616b04a717b)

If Celery cannot be compatible with asyncio, then performing database operations within tasks will be affected.

**Comment by wu-clan** [comment]
Hi, @downdawn 
Has successfully run the asynchronous task with a temporary solution, see pr TODO for details.

**Comment by downdawn** [comment]
nice
