### ISSUE TITLE
Multi-tab refresh results in 404 error

### ISSUE THREAD

**Issue by isteven-xu** [fastapi-practices/fastapi_best_architecture#323]
Multi-tab refresh results in 404 error
多标签刷新单个页签重定向到/，报404

**Comment by wu-clan** [comment]
没懂，详细点或者截图？

**Comment by isteven-xu** [comment]
> 没懂，详细描述或者截图

![image](https://github.com/fastapi-practices/fastapi_best_architecture/assets/32054226/1c8bda8a-cec9-4f57-808b-e1ecd046a214)
这里点击刷新404

**Comment by wu-clan** [comment]
前端问题将自动关闭
