### ISSUE TITLE
当返回json数据比较大时，api返回延迟很高

### ISSUE THREAD

**Issue by nipeone** [fastapi-practices/fastapi_best_architecture#324]
一个大约6M的json内容，通过ResponseModel返回，大约需要3.5s。而用原生fastapi大约需要0.17s。初步判断是opera_log_middleware中的问题，因为将此中间件注释后返回延迟也降到0.17s左右。
[test.json](https://github.com/fastapi-practices/fastapi_best_architecture/files/15478235/test.json)

**Comment by wu-clan** [comment]
我们会积极调查此事件，感谢反馈

**Comment by wu-clan** [comment]
这是我的测试代码：
```py
@router.get('/test/lf')
async def get_lf():
    async with aiofiles.open('/Users/null/Downloads/test.json') as f:
        data = await f.read()
        import orjson
        data = orjson.loads(data)
    # return await response_base.success(data=data)
    return {'data': data}
```
此中间件的开启和关闭在两种返回方式响应时间上几乎没有差别

或者，你能提供更好的 MRE 用于我本地测试吗？

**Comment by nipeone** [comment]
最新的代码和我昨天测试的现象稍有不同，我也继续跟踪哪里的问题，这是我的测试代码
file: api/v1/monitor/server.py
```
with open('/opt/test.json') as f:
    data = f.read()
    import orjson
    data = orjson.loads(data)

from backend.utils.serializers import MsgSpecJSONResponse
@router.get('/test/lf/a', summary='server 测试')
async def get_lf_a():

    return {'data': data}

@router.get('/test/lf/b', summary='server 测试')
async def get_lf_b():

    return MsgSpecJSONResponse({'data': data})

@router.get('/test/lf/c', summary='server 测试')
async def get_lf_c():

    return await response_base.success(data=data)
```
test.py
```
import requests
import time
import orjson

def handler(x):
    response = requests.get(f"http://127.0.0.1:8000//api/v1/monitors/server/test/lf/{x}")
    j = orjson.loads(response.text)
    return j

def main():
    t1=time.time()
    handler('a')
    t2=time.time()
    handler('b')
    t3=time.time()
    handler('c')
    t4=time.time()
    print(f'direct return        cost:{t2-t1:.3f}s')
    print(f'MsgSpecJSONResponse  cost:{t3-t2:.3f}s')
    print(f'ResponseModel        cost:{t4-t3:.3f}s')

if __name__ == '__main__':
    main()
```

三种返回延迟各不相同
MIDDLEWARE_GZIP: bool = True时：
添加app.add_middleware(OperaLogMiddleware)
direct return        cost: 3.821s
MsgSpecJSONResponse  cost: 1.784s
ResponseModel        cost: 3.765s

MIDDLEWARE_GZIP: bool = True时：
注释app.add_middleware(OperaLogMiddleware)
direct return        cost: 3.341s
MsgSpecJSONResponse  cost: 1.767s
ResponseModel        cost: 3.620s

MIDDLEWARE_GZIP: bool = False时：
添加app.add_middleware(OperaLogMiddleware)
direct return        cost: 1.727s
MsgSpecJSONResponse  cost: 0.220s
ResponseModel        cost: 2.086s

MIDDLEWARE_GZIP: bool = False时：
注释app.add_middleware(OperaLogMiddleware)
direct return        cost: 1.732s
MsgSpecJSONResponse  cost: 0.205s
ResponseModel        cost: 2.076s

**Comment by wu-clan** [comment]
我将尝试使用 anyio 和 run_in_threadpool 方法替换 OperaLogMiddleware 中的 task，这里的性能损耗相对较小，因为大型 json 返回并没有到处可见

令我感到惊讶的是，MsgSpecJSONResponse 已经用作 fastapi 的默认序列化器，但再次使用，竟会有如此大的速度提升

相比之下，更应该考虑 GZIP 中间件的性能损耗，如此之大

**Comment by nipeone** [comment]
有简单做过一个测试，MsgSpecJSONResponse作为默认序列化器貌似没起什么作用。

**Comment by wu-clan** [comment]
查看性能讨论 #265，我想直接使用 MsgSpecJSONResponse 加速是有道理的，因为在 MsgSpecJSONResponse 作为默认序列器起生效之前，性能损失可能来自 fastapi 默认的 pydantic 序列化，如果添加一个 orjson 返回的测试，或许对比性也将存在

**Comment by wu-clan** [comment]
GZIP 中间件在 dev 模式中，用作响应压缩，线上模式，通常采用 nginx 实施，如果它的影响如此之大，我认为完全可以删除它，因为 dev 模式下压缩意义不大，并且，此中间件内部存在同步 io 操作，这可能是重要影响因素

**Comment by nipeone** [comment]
> 查看性能讨论 #265，我想直接使用 MsgSpecJSONResponse 加速是有道理的，因为在 MsgSpecJSONResponse 作为默认序列器起生效之前，性能损失可能来自 fastapi 默认的 pydantic 序列化，如果添加一个 orjson 返回的测试，或许对比性也将存在

关于这一点稍有不明白，default_response_class=MsgSpecJSONResponse的作用不是指明序列化器吗？fastapi还会再调用pydantic序列化吗？还是说数据对象在进MsgSpecJSONResponse之前会受到pydantic的validation？

**Comment by wu-clan** [comment]
default_response_class 只用作最终返回，在此之前，fastapi 会在内部提前序列化数据（pydantic / jsonable_encoder）然后再返回

如果接口直接返回序列化后的数据（字典），那么 fastapi 在内部的提前序列化就变为了简单地处理字典数据，所以会更快

**Comment by nipeone** [comment]
that's great! 再把BackgroundTask(OperaLogService.create, obj_in=opera_log_in)改为anyio或者asyncio的后台执行任务，性能损耗就很小了

**Comment by wu-clan** [comment]
在原有的接口基础上添加此接口：

```py
@router.get('/test/lf/d')
async def get_lf_d():
    return ORJSONResponse({'code': 200, 'msg': '', 'data': data})
```

测试代码：

```py
import asyncio

import httpx
import time
import orjson

retry_count = 10


def retry(num: int):
    def _iter(func: callable):
        async def wrapper(x: str):
            for _ in range(num):
                await func(x)

        return wrapper

    return _iter


@retry(retry_count)
async def handler(x):
    async with httpx.AsyncClient(verify=False, timeout=10) as client:
        response = await client.get(f"http://127.0.0.1:8000/api/v1/monitors/server/test/lf/{x}")
        j = orjson.loads(response.text)
        return j


async def main():
    t1 = time.time()
    await handler('a')
    t2 = time.time()
    await handler('b')
    t3 = time.time()
    await handler('c')
    t4 = time.time()
    await handler('d')
    t5 = time.time()
    print(f'direct return        cost:{(t2 - t1) / retry_count:.3f}s')
    print(f'MsgSpecJSONResponse  cost:{(t3 - t2) / retry_count:.3f}s')
    print(f'ResponseModel        cost:{(t4 - t3) / retry_count:.3f}s')
    print(f'orjson               cost:{(t5 - t4) / retry_count:.3f}s')


if __name__ == '__main__':
    asyncio.run(main())
```

MIDDLEWARE_GZIP: bool = False
MIDDLEWARE_OPERA: bool = True (BackgroundTask)

```
direct return        cost:2.217s
MsgSpecJSONResponse  cost:0.225s
ResponseModel        cost:2.335s
orjson               cost:0.223s
```

MIDDLEWARE_GZIP: bool = False
MIDDLEWARE_OPERA: bool = True (asyncio task)

```
direct return        cost:1.955s
MsgSpecJSONResponse  cost:0.225s
ResponseModel        cost:2.264s
orjson               cost:0.229s
```

MIDDLEWARE_GZIP: bool = False
MIDDLEWARE_OPERA: bool = True (anyio task)

```
direct return        cost:2.066s
MsgSpecJSONResponse  cost:0.223s
ResponseModel        cost:2.343s
orjson               cost:0.224s
```
