### ISSUE TITLE
组织管理无法搜索三级以上的子组织

### ISSUE THREAD

**Issue by Arterning** [fastapi-practices/fastapi_best_architecture#338]
## Describe the bug
组织管理无法搜索三级以上的子组织

## To Reproduce
建立A->B->C 这样的三级组织，搜索C组织的名称，无法展示C组织的搜索结果

## Expected behavior
应该展示C组织的搜索结果

**Comment by Arterning** [comment]
I have a simple fix for this issue: https://github.com/Arterning/fastapi_best_architecture/commit/f6f4e9f1aaa460fe89d0a34065a5cc68bca94c98

**Comment by wu-clan** [comment]
感谢提出此问题，请问你可以提交pr吗？我们会对比进行审阅

**Comment by Arterning** [comment]
可以，我已提交PR
https://github.com/fastapi-practices/fastapi_best_architecture/pull/339
