### ISSUE TITLE
怎么把 MySQL 切换成 PG

### ISSUE THREAD

**Issue by DimplesY** [fastapi-practices/fastapi_best_architecture#353]
想请教一下怎么把 MySQL 切换成 PG，有好的方案吗

**Comment by wu-clan** [comment]
暂时没有研究过

**Comment by DimplesY** [comment]
> 暂时没有研究过

有考虑出一个 PG 的版本吗，我可以贡献一下

**Comment by wu-clan** [comment]
你可以直接切换试一下，目前没有涉及到什么特定类型，不知道能不能无缝切换

**Comment by wu-clan** [comment]
如果不兼容，也不会做这么复杂的pg版本，最多只会像 [fsm](https://github.com/fastapi-practices/fastapi_sqlalchemy_mysql) 一样的简易版本
