### ISSUE TITLE
自动生成代码报错

### ISSUE THREAD

**Issue by jundaychan** [fastapi-practices/fastapi_best_architecture#354]
在model层，生成的部分未引入，comment没有带引号：
![image](https://github.com/user-attachments/assets/e8ced705-2f08-4438-96cb-cadfcb2c5251)
同时model层，缺少init文件，导致crud和service都导入失败
![image](https://github.com/user-attachments/assets/4bc5f7d1-4352-48d9-a07b-ed1913e05fd9)

**Comment by wu-clan** [comment]
some fix: #356
