### ISSUE TITLE
最近还会有大的版本吗？

### ISSUE THREAD

**Issue by jundaychan** [fastapi-practices/fastapi_best_architecture#36]
感谢分享，我实践了做了个爬虫项目，写起来项目结构清晰和部署简单。

但是刚做完就更新3.10后版本了，想问下还会进行大的改版吗？尤其是在项目结构上。

**Comment by wu-clan** [comment]
可以在这里跟踪我们 #35

**Comment by jundaychan** [comment]
> 可以在这里跟踪我们 #35

感谢提示，非常钦佩您的开源精神，我会把一些我认为的需求提上去，如果有机会我会pr，谢谢！

**Comment by wu-clan** [comment]
你好, @jundaychan 

我尝试通过ruff做兼容，但是不幸的是，ruff可以通过pyupgrade规则自动更新至高版本语法，但并不支持版本回退，并且，将没有自动修复

所以，它似乎不能自动向前兼容python版本，如果你在继续使用3.8，或许这些可以帮到你，但请注意，这不会检测到意外的高版本特性

1. 修改`.ruff.toml`文件，注释掉选择规则： `I002, F404, UP007`，将 `-target-version` 改为所需版本, 添加一条规则
```
[pyupgrade]
keep-runtime-typing = true
```
2. 修改`.pre-commit-config.yaml`中的 black 配置，将`language_version`, `--target-version`改为需要的版本
3. 在根目录下运行`pre-commit run --all-files --verbose`

**Comment by jundaychan** [comment]
> 你好, @jundaychan
> 
> 我尝试通过ruff做兼容，但是不幸的是，ruff可以通过pyupgrade规则自动更新至高版本语法，但并不支持版本回退，并且，将没有自动修复
> 
> 所以，它似乎不能自动向前兼容python版本，如果你在继续使用3.8，或许这些可以帮到你，但请注意，这不会检测到意外的高版本特性
> 
> 1. 修改`.ruff.toml`文件，注释掉选择规则： `I002, F404, UP007`，将 `-target-version` 改为所需版本, 添加一条规则
> 
> ```
> [pyupgrade]
> keep-runtime-typing = true
> ```
> 
> 2. 修改`.pre-commit-config.yaml`中的 black 配置，将`language_version`, `--target-version`改为需要的版本
> 3. 在根目录下运行`pre-commit run --all-files --verbose`

谢谢wu-clan 我已经全部改成3.10版本了，这样能更好的支持 str | int 之类的语法，写起来也更轻松

**Comment by wu-clan** [comment]
好极了🎉
