### ISSUE TITLE
response_base.fail()  and exception handler questions

### ISSUE THREAD

**Issue by seoulkimchi88** [fastapi-practices/fastapi_best_architecture#377]
Hi.
First, I'd like to express my gratitude for sharing this wonderful project. I've learned a lot from it—so much that it's hard to quantify. I'm still diving deeper into FastAPI, and I have a few questions.

1.  When using `response_base.fail()` to return an error response, the HTTP response header retains a status code of `200`. Is there a specific reason for not using the actual error code in the HTTP header? For instance, in the case of a DELETE API call where the ID is not found, the header returns a `200` status code.
    
   ![image](https://github.com/user-attachments/assets/9c25ddf3-4d62-405e-8ffb-ba4beb488f76)

2. For custom exceptions like ForbiddenError, NotFoundError, and others derived from BaseExceptionMixin, how can I catch these exceptions in the exception handler so that the traceback does not propagate? I expected that these would be handled by `all_exception_handler(request: Request, exc: Exception), but it seems that the ASGI traceback is the one logged.

   ![image](https://github.com/user-attachments/assets/3b23f399-2fb3-4d6f-b637-f207e93d08c7)
   ![image](https://github.com/user-attachments/assets/671668bb-b732-4a64-8727-084c2ceefcc5)

   My goal is to log appropriate error messages in the log file for specific exceptions like `ForbiddenError` and `NotFoundError`

3. In the routers, how can I include a Pydantic schema, such as GetApiListDetails, in the router response along with the ResponseModel so that it is automatically displayed in the openapi docs?

I'm not sure if my questions make sense but any insights or guidance on best practices would be greatly appreciated.. 

Thank you very much . ❤️

**Comment by wu-clan** [comment]
Hello. Sorry I'm late.

1. Please see our Design Realization #222
The interface status code can only be realized through the interface status_code parameter or by returning JsonResponse(status_code=xxx).
For the case where `response_base.fail()` has a status code of 200, I think that the interface access actually succeeded, just that some reason (e.g., the database didn't retrieve the data for the operation).
2. You're right, you can log the appropriate error messages for a specific exception with `all_exception_handler(request: Request, exc: Exception)`, the error backtracking occurs with `log.exception(e)`, you just have to search the full text and remove them
3. ResponseModel is more to unify the response information structure, GetApiListDetails is to serialize the return result, if you want to include GetApiListDetails to the openapi document, I think it is feasible, but this may lose the unification of the response structure, so you may also need to customize the GetApiListDetails schema, for example:
    ```py
    class GetApiListDetailsRes(SchemaBase).
        code: int = 200
        msg: str = 'OK'
        data: GetApiListDetails
    ```
    At the interface:
    ```py
    async def get_xx() -> GetApiListDetailsRes.
        # coding
        return GetApiListDetailsRes(data=GetApiListDetails(xxx))
    ```

**Comment by seoulkimchi88** [comment]
@wu-clan thank you for a very detailed reponse.
