### ISSUE TITLE
何时使用sqlalchemy-crud-plus1.0

### ISSUE THREAD

**Issue by isooops** [fastapi-practices/fastapi_best_architecture#381]
感觉 sqlalchemy-crud-plus1.0 版本巨强， 要是用到 [fastapi_best_architecture](https://github.com/fastapi-practices/fastapi_best_architecture) 项目 无敌了

**Comment by wu-clan** [comment]
待 sqlalchemy-crud-plus 文档写完上线之时

**Comment by wu-clan** [comment]
rl. https://github.com/fastapi-practices/sqlalchemy-crud-plus/pull/12
