### ISSUE TITLE
代码生成问题

### ISSUE THREAD

**Issue by luqijun** [fastapi-practices/fastapi_best_architecture#392]
**问题1**：生成crud.py文件时，CRUDPlus没有`select_model_by_id`方法，只有`select_model`方法。
**问题2**：生成api.py文件时，调用接口报错：TypeError: object ResponseModel can't be used in 'await' expression，return后面应该去掉`await`。

**Comment by wu-clan** [comment]
谢谢，后面的升级代码生成还没有适配
