### ISSUE TITLE
[bug]更新用户状态、超级管理员、后台登录问题

### ISSUE THREAD

**Issue by luqijun** [fastapi-practices/fastapi_best_architecture#395]
更新用户状态、超级管理员、后台登录时，获取用户信息应当使用参数`pk`而不是`request.user.id` 。相应地，从redis缓存中删除用户也应该使用`pk`。
[/backend/app/admin/service/user_service.py#L168](https://github.com/fastapi-practices/fastapi_best_architecture/blob/8765f833d286b9fb5a5d7b93b4f9c9a31d213f6e/backend/app/admin/service/user_service.py#L168)
[/backend/app/admin/service/user_service.py#L170](https://github.com/fastapi-practices/fastapi_best_architecture/blob/8765f833d286b9fb5a5d7b93b4f9c9a31d213f6e/backend/app/admin/service/user_service.py#L170)。

**Comment by wu-clan** [comment]
感谢反馈
