### ISSUE TITLE
生成代码报错

### ISSUE THREAD

**Issue by georgeJzzz** [fastapi-practices/fastapi_best_architecture#398]
1. 查询当前数据库表 `sys_opera_log`, 无结果。 是否操作问题呢
![image](https://github.com/user-attachments/assets/589209e9-8bb4-4ea4-8d4b-3e5db6e673e7)

2. 创建模型列, 无法确定提交， 这块是否前端校验问题？
![image](https://github.com/user-attachments/assets/c9e4b440-6674-4eb5-a456-f2455fa4881d)

**Comment by wu-clan** [comment]
1. 数据库名，非数据库表名
2. 我稍后排查一下

**Comment by wu-clan** [comment]
此问题已修复，问题即将关闭
