### ISSUE TITLE
请教一下 server 监控接口里获取server info 为什么要去掉run_in_threadpool方法？

### ISSUE THREAD

**Issue by seanli-lol** [fastapi-practices/fastapi_best_architecture#401]
请教一下 server_info.get_cpu_Info 里有 time.sleep(interval), 为什么要去掉run_in_threadpool而是直接调用呢？

**Comment by wu-clan** [comment]
server 监控接口里面调用的无论是 io 密集型还是 cpu 密集型任务，经过测试，使用 run_in_threadpool 方法都没有实质性的加速效果，为了减少干扰，所以直接去掉了

**Comment by seanli-lol** [comment]
确实使用 run_in_threadpool 方法对这个接口没有加速效果，异步函数里调用同步的time.sleep不会阻塞协程的切换从而导致拖慢整个loop循环吗

**Comment by wu-clan** [comment]
我认为并不会

https://github.com/fastapi/fastapi/blob/9b2a9333b3b9820082deb35605c0619bd578baee/fastapi/routing.py#L202-L212

**Comment by seanli-lol** [comment]
了解了，谢谢

**Comment by seanli-lol** [comment]
我仿造server监控接口编写如下demo时，
先调用 /foo 接口，该接口一直阻塞等待返回，
再调用 / 接口时，同样会被阻塞
`import time

import uvicorn
from fastapi import FastAPI
from path import Path

app = FastAPI()


def io_block():
    time.sleep(999)
    return "blocked over"


@app.get("/")
async def read_root():
    return {"Hello": "World"}


@app.get("/foo")
async def read_item():
    res = io_block()
    return {"res": res}


if __name__ == '__main__':
    try:
        config = uvicorn.Config(app=f'{Path(__file__).stem}:app', reload=True)
        server = uvicorn.Server(config)
        server.run()
    except Exception as e:
        raise e
`

**Comment by wu-clan** [comment]
谢谢你的MRE，经过测试，我相信你是对的，我会稍后修复这个问提，并且，我会深度探索一下这个问题
