### ISSUE TITLE
celery应用功能异常

### ISSUE THREAD

**Issue by tcsuda** [fastapi-practices/fastapi_best_architecture#424]
**### 异常**
1. app/task/api/v1/task.py  中  response_base 无法序列化 AsyncResult 对象，涉及， 获取任务状态， 获取任务结果， 调用执行任务 
2. 获取所有可执行任务 与 获取当前正在执行的任务 不起作用

**Comment by wu-clan** [comment]
感谢反馈，我会调查此事
