### ISSUE TITLE
Abnormal Custom Form Structure in Swagger UI

### ISSUE THREAD

**Issue by downdawn** [fastapi-practices/fastapi_best_architecture#43]
The default form login return structure must be:

`{"access_token": access_token, "token_type": "bearer"}`

Otherwise, the swagger ui cannot request correctly, even if the verification passes

expectation is
```
{
  "code": 200,
  "msg": "Success",
  "data": {
        {"access_token": access_token, "token_type": "bearer"}
}
}
```

**Comment by downdawn** [comment]
The structure returned using fastapi_pagination is also not expected

**Comment by downdawn** [comment]
If it cooperates with the front end, it is best to have a unified structure

**Comment by wu-clan** [comment]
I checked the entire source code of fastapi and the questions in the repository, but I didn‘t find the relevant token custom structure method.🥲

**Comment by downdawn** [comment]
Yes, I have also looked for it...

There is also a question regarding how to implement the logout interface?

Normally, tokens can be stored in a database such as Redis for proper implementation.

**Comment by downdawn** [comment]
There is actually a compromise solution, which involves having two login interfaces.

The "login" interface is used by the frontend and accepts JSON format for login.

The "login2" interface is used by the API documentation and accepts form format for login.

**Comment by wu-clan** [comment]
I checked several fastapi-related projects that are live and no one is using swagger

**Comment by wu-clan** [comment]
My initial solution: the form is only used for swaager, and the on-line is changed to json (the one with comments)

**Comment by wu-clan** [comment]
I'm implementing the solution right now PR
