### ISSUE TITLE
代码生成器的问题

### ISSUE THREAD

**Issue by Crain99** [fastapi-practices/fastapi_best_architecture#439]
![image](https://github.com/user-attachments/assets/bd181a8e-b3c4-4f51-832f-a7a64a62e1fc)
在原始数据表中有关于datetime的列时需要手动导入依赖

**Comment by Crain99** [comment]
schema 也有同样的问题

**Comment by Crain99** [comment]
还有生成的代码在api目录下确实__init__.py的文件

**Comment by Crain99** [comment]
目前我先弃用了代码生成器，bug确实还多
![image](https://github.com/user-attachments/assets/d708014a-ea7f-4ee0-84d3-9c9f0e77991a)
简单的查询也有点儿问题 哈哈
另外项目确实很不错！！！

**Comment by Crain99** [comment]
![image](https://github.com/user-attachments/assets/ac6bf8d2-858d-45b2-8271-9ae4878bc86b)
![image](https://github.com/user-attachments/assets/03ddab33-b58d-48c5-8c66-9a538c3efc6b)
没有找到get_select()方法

**Comment by wu-clan** [comment]
好的，因为 fba 内部的使用 [sqlalchemy-crud-plus](https://github.com/fastapi-practices/sqlalchemy-crud-plus)，前段时间更新了几个版本，fba 内部可能存在遗漏（没有同步更新到）

**Comment by wu-clan** [comment]
fixed.
