### ISSUE TITLE
菜单管理的问题

### ISSUE THREAD

**Issue by Crain99** [fastapi-practices/fastapi_best_architecture#448]
![image](https://github.com/user-attachments/assets/c9f3c3c6-9845-4a88-b42e-41f285262eb7)
如图 我新建了一个菜单， 但是左侧菜单栏无法正常的显示和加载 是哪里操作不对吗 能发出个教程

**Comment by wu-clan** [comment]
就目前而言，这种情况是对的，菜单名为了兼容i18n，读的前端，你前端没写路由和界面，加载不出来是正常的
