### ISSUE TITLE
BackgroundTasks task is invalid

### ISSUE THREAD

**Issue by downdawn** [fastapi-practices/fastapi_best_architecture#81]
1、Trying to log in, the background task creation login log is not executed, and the database has no data.

2、An exception occurs when logging in in json format
```
UnboundLocalError: local variable 'login_logs_params' referenced before assignment
```

**Comment by wu-clan** [comment]
Everything works fine locally for me, nothing unusual, did you try to sync the code?

**Comment by downdawn** [comment]
Magic. I pull the latest code, recreate the table

**Comment by wu-clan** [comment]
Is the problem solved? I recreated the database table and still did not encounter the exception

**Comment by downdawn** [comment]
I re-fork the project, re-create the environment, the same error

**Comment by downdawn** [comment]
```
            except errors.AuthorizationError as e:
                login_logs_params.update({'status': 0, 'msg': e.msg})
```

An AuthorizationError exception is thrown, login_logs_params has not been set

**Comment by downdawn** [comment]
Background tasks will run only after the response(after the response is successful).

[https://github.com/tiangolo/fastapi/issues/2604](https://github.com/tiangolo/fastapi/issues/2604)

**Comment by wu-clan** [comment]
The problem has been fixed, please check the PR for details.
